#!/bin/bash

set -euo pipefail

#####################################################
# This algorithm is implemented in the scikit-learn
# software package (http://scikit-learn.org/stable/).
#####################################################

trainingFilePath="$1"
testFilePath="$2"
classOptions="$3"

python AlgorithmScripts/Helper/sklearn_c_generic.py "$trainingFilePath" "$testFilePath" "$classOptions" "clf = BaggingClassifier(base_estimator=SVC(), n_estimators=1000, max_samples=1.0, max_features=1.0, bootstrap=False, bootstrap_features=False, oob_score=False, warm_start=False, n_jobs=1, random_state=R_SEED, verbose=0)" 2>&1 | python AlgorithmScripts/Helper/ReformatSklearnOutput.py $classOptions
