#!/bin/bash

rm -rfv ../Classification/tsv/sklearn/* ../FeatureSelection/tsv/sklearn/*

function createScript {
  algorithmType=$1
  templateFile=$2
  algorithm=$3
  parameterDescription=$4

  scriptDir=../$algorithmType/tsv/sklearn/$algorithm

  mkdir -p $scriptDir

  cp -v $templateFile $scriptDir/$parameterDescription
}

#for algorithm in lda logistic_regression qda sgd svm_linear svm_nurbf svm_poly svm_rbf svm_sigmoid knn bagging decision_tree extra_trees random_forest
for algorithm in lda logistic_regression qda sgd svm_linear svm_nurbf svm_poly svm_rbf knn bagging decision_tree extra_trees random_forest
do
  createScript Classification sklearn_c_template $algorithm default
done

for algorithm in anova random_forest_rfe random_lasso random_logistic_regression svm_rfe
do
  createScript FeatureSelection sklearn_fs_template $algorithm default
done
