#!/bin/bash

set -euo pipefail

showStats=False
#showStats=True

rm -rf ../Classification/tsv/mlr/* ../FeatureSelection/tsv/mlr/*
python3 build_mlr_scripts.py $showStats

rm -rf ../Classification/tsv/sklearn/* ../FeatureSelection/tsv/sklearn/*
python3 build_sklearn_scripts.py $showStats

rm -rf ../Classification/arff/weka/* ../FeatureSelection/arff/weka/*
python3 build_weka_scripts.py $showStats

rm -rf ../Classification/tsv/keras/*
python3 build_keras_scripts.py $showStats
