#!/bin/bash

set -euo pipefail

rm -rf ../Classification/tsv/sklearn/* ../FeatureSelection/tsv/sklearn/*
python3 build_sklearn_scripts.py

rm -rf ../Classification/tsv/mlr/* ../FeatureSelection/tsv/mlr/*
python3 build_mlr_scripts.py

rm -rf ../Classification/arff/weka/* ../FeatureSelection/arff/weka/*
python3 build_weka_scripts.py
