#!/bin/bash

set -o errexit
set -o pipefail

trainingFilePath="$1"
testFilePath="$2"
classOptions="$3"
callingScript="$4"

dirName=$(dirname $0)

algorithm=$(dirname $callingScript)
algorithm=$(basename $algorithm)

parameterDescription=$(basename $callingScript)

Rscript --vanilla $dirName/mlr_c_generic.R "$trainingFilePath" "$testFilePath" "$classOptions" "classif.${algorithm}" "$parameterDescription" 2>&1 | python $dirName/ReformatMlrClassificationOutput.py "$classOptions"
#Rscript --vanilla $dirName/mlr_c_generic.R "$trainingFilePath" "$testFilePath" "$classOptions" "classif.${algorithm}" "$parameterDescription"
