#!/bin/bash

set -o errexit
set -o pipefail

dataFilePath="$1"
callingScript="$2"

dirName=$(dirname $0)

algorithm=$(dirname $callingScript)
algorithm=$(basename $algorithm)

parameterDescription=$(basename $callingScript)

Rscript --vanilla $dirName/mlr_fs_generic.R "$dataFilePath" "$algorithm" "$parameterDescription" 2>&1 | python $dirName/ReformatMlrFeatureSelectionOutput.py
