#!/bin/bash

trainingFilePath="$1"
testFilePath="$2"
classOptions="$3"
useDefaultParameters="$4"
callingScript="$5"

dirName=$(dirname $0)

algorithmAbbreviated=$(python $dirName/ParseAlgorithmName.py $callingScript)

parametersFilePath=
if [[ "$useDefaultParameters" == "false" ]]
then
  parametersFilePath="$dirName/../ParameterCombinations/$callingScript"
fi

Rscript --vanilla $dirName/mlr_c_generic.R "$trainingFilePath" "$testFilePath" "$classOptions" "classif.${algorithmAbbreviated}" "$parametersFilePath" 2>&1 | python $dirName/ReformatOutput.py "$classOptions"
#Rscript --vanilla $dirName/mlr_c_generic.R "$trainingFilePath" "$testFilePath" "$classOptions" "classif.${algorithmAbbreviated}" "$parametersFilePath"
