#!/bin/bash

mlflexDirPath="$1"
dataFilePath="$2"
useDefaultParameters="$3"
callingScript="$4"

dirName=$(dirname $0)

algorithmAbbreviated=$(python $dirName/ParseAlgorithmName.py $callingScript)

parametersFilePath=
if [[ "$useDefaultParameters" == "false" ]]
then
  parametersFilePath="$dirName/../ParameterCombinations/$callingScript"
fi

#Rscript --vanilla $dirName/mlr_fs_generic.R "$dataFilePath" "${algorithmAbbreviated}" "$parametersFilePath"
Rscript --vanilla $dirName/mlr_fs_generic.R "$dataFilePath" "${algorithmAbbreviated}" "$parametersFilePath" 2>&1 | python $dirName/ReformatMlrOutput.py
