#!/bin/bash

set -euo pipefail

trainingFilePath="$1"
testFilePath="$2"
classOptions="$3"
callingScript="$4"

dirName=$(dirname $0)

algorithm=$(dirname $callingScript)
algorithm=$(basename $algorithm)

parameterDescription=$(basename $callingScript)

#python $dirName/sklearn_c_generic.py "$trainingFilePath" "$testFilePath" "$classOptions" "$algorithm" "$parameterDescription" 2>&1 | python $dirName/ReformatSklearnOutput.py $classOptions
python $dirName/sklearn_c_generic.py "$trainingFilePath" "$testFilePath" "$classOptions" "$algorithm" "$parameterDescription"
