#!/bin/bash

#set -o errexit
#set -o pipefail
set -euo pipefail

dataFilePath="$1"
callingScript="$2"

dirName=$(dirname $0)

algorithm=$(dirname $callingScript)
algorithm=$(basename $algorithm)

parameterDescription=$(basename $callingScript)

#python $dirName/sklearn_fs_generic.py "$dataFilePath" "$algorithm" "$parameterDescription"
python $dirName/sklearn_fs_generic.py "$dataFilePath" "$algorithm" "$parameterDescription" 2>&1 | python $dirName/ReformatSklearnOutput.py
