#!/bin/bash

trainingFilePath="$1"
testFilePath="$2"
classOptions="$3"
parameters="$4"

#command_exists () {
#    type "$1" &> /dev/null ;
#}

## Find out amount of memory available
#function getMemAvailable {
#  if command_exists free
#  then
#    mem=$(free -m | tail -n3 | awk '{print $2}' | head -n1)M # Gives total memory in MB (preferred over GB because it always rounds down)
#  else
#    mem=$(top -l 1 | awk '/PhysMem:/ {print $2}' | tr '[:upper:]' '[:lower:]')
#  fi
#
#  echo "$mem"
#}

command_exists () {
    type "$1" &> /dev/null ;
}

## Find out amount of memory available
function getMemAvailable {
  if command_exists free
  then
    mem=$(free -m | tail -n3 | awk '{print $2}' | head -n1)M # Gives total memory in MB (preferred over GB because it always rounds down)
  else
    mem=$(top -l 1 | awk '/PhysMem:/ {print $2}' | tr '[:upper:]' '[:lower:]')
  fi

  echo "$mem"
}

#echo "Testingdef"
#echo $(dirname $0)/../../scripts/helper
#ls $(dirname $0)/../../scripts/helper
#source $(dirname $0)/../../scripts/helper

echo "Testingghi"
#mem=$(getMemAvailable)
exit 1

#wekaLibPath=$(dirname $0)/lib
#classPath="$wekaLibPath/*:$wekaLibPath/wekalib/*"

#echo java -Xmx${mem} -classpath "$classPath" $parameters -t "$trainingFilePath" -T "$testFilePath" -p 0 -distribution | python $(dirname $0)/ReformatClassificationParameters.py | sh | python $(dirname $0)/ParsePredictions.py "$classOptions"
