#!/bin/bash

set -euo pipefail

dataFilePath="$1"
algorithm="$2"

source $(dirname $0)/../../scripts/shared_functions

wekaLibPath=$(dirname $0)/lib
#wekaLibPath=AlgorithmScripts/Helper/lib
classPath="$wekaLibPath/*:$wekaLibPath/wekalib/*"

echo java $(getJavaArgs) -classpath $classPath $algorithm -i $dataFilePath | python3 $(dirname $0)/ReformatWekaFSParams.py | bash | python3 $(dirname $0)/ParseWekaFSResults.py
