#!/bin/bash

set -euo pipefail

#####################################################
# This algorithm is implemented in the scikit-learn
# software package (http://scikit-learn.org/stable/).
#####################################################

trainingFilePath="$1"
testFilePath="$2"
classOptions="$3"

python AlgorithmScripts/Helper/sklearn_c_generic.py "$trainingFilePath" "$testFilePath" "$classOptions" "clf = KNeighborsClassifier(n_neighbors=1, weights='distance', algorithm='auto', leaf_size=30, p=2, metric='minkowski', metric_params=None, n_jobs=1)" 2>&1 | python AlgorithmScripts/Helper/ReformatSklearnOutput.py $classOptions
