#!/bin/bash

set -euo pipefail

#####################################################
# This algorithm is implemented in the scikit-learn
# software package (http://scikit-learn.org/stable/).
#####################################################

trainingFilePath="$1"
testFilePath="$2"
classOptions="$3"

python AlgorithmScripts/Helper/sklearn_c_generic.py "$trainingFilePath" "$testFilePath" "$classOptions" "from sklearn.neighbors import KNeighborsClassifier; clf = KNeighborsClassifier()" 2>&1 | python AlgorithmScripts/Helper/ReformatSklearnOutput.py $classOptions
