#!/bin/bash

mlflexDirPath="$1"
trainingFilePath="$2"
testFilePath="$3"
classOptions="$4"

parameters='weka.classifiers.meta.RandomCommittee -S 1 -I 10 -W weka.classifiers.trees.RandomTree -- -K 0 -M 1.0 -S 1'

sh "$(dirname $0)"/Helper/weka_c_generic "$mlflexDirPath" "" "$trainingFilePath" "$testFilePath" "$parameters" "$classOptions"
