#!/bin/bash

mlflexDirPath="$1"
trainingFilePath="$2"
testFilePath="$3"
classOptions="$4"

parameters='weka.classifiers.misc.CHIRP -V 7 -S 1'
classPath="$mlflexDirPath/lib/CHIRP.jar"

sh "$(dirname $0)"/Helper/weka_c_generic "$mlflexDirPath" "$classPath" "$trainingFilePath" "$testFilePath" "$parameters" "$classOptions"
