#!/bin/bash

set -euo pipefail

#######################################################################################
# This algorithm is implemented in the mlr software package (http://mlr-org.github.io).
#######################################################################################

dataFilePath="$1"

Rscript --no-save --no-restore --no-site-file --no-init-file --no-environ --max-ppsize=500000 AlgorithmScripts/Helper/mlr_f_generic.R "$dataFilePath" "cforest.importance" 2>&1 | python AlgorithmScripts/Helper/ReformatMlrFeatureSelectionOutput.py
