#!/bin/bash

##########################################################
# This algorithm is implemented in the weka
# software package (http://www.cs.waikato.ac.nz/ml/weka/).
##########################################################

bash AlgorithmScripts/Helper/weka_f_generic "$1" 'weka.attributeSelection.OneRAttributeEval -S 1 -F 10 -B 6 -s "weka.attributeSelection.Ranker -T -1.7976931348623157E308 -N -1"'
