#!/bin/bash

mlflexDirPath="$1"
trainingFilePath="$2"
testFilePath="$3"
classOptions="$4"

parameters='weka.classifiers.trees.RandomForest -I 100 -K 0 -S 1'

sh "$(dirname $0)"/Helper/weka_c_generic "$mlflexDirPath" "" "$trainingFilePath" "$testFilePath" "$parameters" "$classOptions"
