#!/bin/bash

##########################################################
# This algorithm is implemented in the weka
# software package (http://www.cs.waikato.ac.nz/ml/weka/).
##########################################################

bash AlgorithmScripts/Helper/weka_c_generic "$1" "$2" "$3" "$4" "weka.classifiers.trees.J48 -U  -B -M 2   "
