#!/bin/bash

set -euo pipefail

#######################################################################################
# This algorithm is implemented in the mlr software package (http://mlr-org.github.io).
#######################################################################################

trainingFilePath="$1"
testFilePath="$2"
classOptions="$3"
numCores="$4"
verbose="$5"

#export PYTHONIOENCODING="UTF-8"
Rscript --no-save --no-restore --no-site-file --no-init-file --no-environ --max-ppsize=500000 AlgorithmScripts/Helper/mlr_c_generic.R "$trainingFilePath" "$testFilePath" "$classOptions" "$numCores" "'classif.C50', subset = FALSE, winnow = FALSE, noGlobalPruning = TRUE, CF = 0.25, minCases = 2, fuzzyThreshold = FALSE, sample = 0, earlyStopping = TRUE"
#2>&1 | python3 AlgorithmScripts/Helper/ReformatMlrClassificationOutput.py "$classOptions" "$verbose"
