#!/bin/bash

set -euo pipefail

source scripts/shared_functions
source scripts/first_param_check

dataFiles="$(python scripts/ParseArgs.py --data TRUE TRUE $@)"
description="$(python scripts/ParseArgs.py --description TRUE TRUE $@)"
numIterations="$(python scripts/ParseArgs.py --iterations TRUE TRUE $@)"
verbose="$(python scripts/ParseArgs.py --verbose FALSE FALSE $@)"
classifAlgos="$(python scripts/ParseArgs.py --classif-algo TRUE TRUE "$@")"
outputDir="$(python scripts/ParseArgs.py --output-dir TRUE TRUE $@)"

checkParamParseOutput "$dataFiles"
checkParamParseOutput "$description"
checkParamParseOutput "$numIterations"
checkParamParseOutput "$verbose"
checkParamParseOutput "$classifAlgos"
checkParamParseOutput "$outputDir"

debug="$(convertVerboseToDebug "$verbose")"
outPredictionsFile="$outputDir/Predictions.tsv"
outMetricsFile="$outputDir/Metrics.tsv"
outBenchmarkFile="$outputDir/ElapsedTime.tsv"
outLogFile="$outputDir/Log.txt"

mkdir -p $outputDir

source scripts/print_args

scripts/classification "$dataFiles" "$description" "$numIterations" "$debug" "$classifAlgos" "$outPredictionsFile" "$outMetricsFile" "$outBenchmarkFile" montecarlo 0 2>&1 | tee -a "$outLogFile"

source scripts/success_message
