#!/bin/bash

set -euo pipefail

source scripts/shared_functions
source scripts/first_param_check

dataFiles="$(python scripts/ParseArgs.py --data TRUE TRUE $@)"
description="$(python scripts/ParseArgs.py --description TRUE TRUE $@)"
numIterations="$(python scripts/ParseArgs.py --iterations TRUE TRUE $@)"
numFolds="$(python scripts/ParseArgs.py --folds TRUE TRUE $@)"
verbose="$(python scripts/ParseArgs.py --verbose FALSE FALSE $@)"
classifAlgos="$(python scripts/ParseArgs.py --classif-algo TRUE TRUE "$@")"
outputDir="$(python scripts/ParseArgs.py --output-dir TRUE TRUE $@)"

checkParamParseOutput "$dataFiles"
checkParamParseOutput "$description"
checkParamParseOutput "$numIterations"
checkParamParseOutput "$numFolds"
checkParamParseOutput "$verbose"
checkParamParseOutput "$classifAlgos"
checkParamParseOutput "$outputDir"

debug="$(convertVerboseToDebug "$verbose")"
outPredictionsFile="$outputDir/Predictions.tsv"
outMetricsFile="$outputDir/Metrics.tsv"
outBenchmarkFile="$outputDir/ElapsedTime.tsv"
outLogFile="$outputDir/Log.txt"

mkdir -p $outputDir

source scripts/print_args

tmpDir=$(mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir')

function cleanup_cv {
  rm -rf $tmpDir
}

cleanup_cv

for iteration in $(seq 1 $numIterations)
do
  outDir=$tmpDir/$iteration
  mkdir -p $outDir

  if [[ "$outPredictionsFile" == "" ]]
  then
    outPredictionsFileIteration=
  else
    outPredictionsFileIteration=$outDir/outpreds
  fi
  if [[ "$outMetricsFile" == "" ]]
  then
    outMetricsFileIteration=
  else
    outMetricsFileIteration=$outDir/outmetrics
  fi
  if [[ "$outBenchmarkFile" == "" ]]
  then
    outBenchmarkFileIteration=
  else
    outBenchmarkFileIteration=$outDir/outbench
  fi

  echo
  echo "**************************************************************" | tee -a "$outLogFile"
  echo "Beginning analysis for cross-validation fold ${iteration}" | tee -a "$outLogFile"
  echo "**************************************************************" | tee -a "$outLogFile"
  scripts/classification "$dataFiles" "$description" "$numFolds" "$debug" "$classifAlgos" "$outPredictionsFileIteration" "$outMetricsFileIteration" "$outBenchmarkFileIteration" crossvalidation $iteration 2>&1 | tee -a "$outLogFile"
done

echo
echo "**************************************************************" | tee -a "$outLogFile"
echo "Finalizing analysis"
echo "**************************************************************" | tee -a "$outLogFile"
echo

echo "Combining results across cross-validation iterations..." | tee -a "$outLogFile"
python scripts/CombineCrossValidationIterations.py "$tmpDir/*/outpreds,$tmpDir/*/outmetrics,$tmpDir/*/outbench" "$tmpDir/outpreds,$tmpDir/outmetrics,$tmpDir/outbenchmark" 2>&1 | tee -a "$outLogFile"

sortCriteria="-k1,1 -k2,2n -k3,3n -k4"
sortFile $tmpDir/outpreds "$sortCriteria" "$outPredictionsFile"
sortFile $tmpDir/outmetrics "$sortCriteria" "$outMetricsFile"
sortFile $tmpDir/outbenchmark "$sortCriteria" "$outBenchmarkFile"

cleanup_cv

source scripts/success_message
