#!/bin/bash

set -o errexit
set -o pipefail

source scripts/firstcheck

dataFiles="$1"
description="$2"
numIterations="$3"
debug="$4"
classifAlgos="$5"
outPredictionsFile="$6"
outMetricsFile="$7"
outBenchmarkFile="$8"
outLogFile="$9"

if [[ "$outLogFile" == "" ]]
then
  echo An output log file must be specified.
  exit 1
fi

source scripts/print_args

scripts/classification "$dataFiles" "$description" "$numIterations" "$debug" "$classifAlgos" "$outPredictionsFile" "$outMetricsFile" "$outBenchmarkFile" montecarlo 0 2>&1 | tee -a "$outLogFile"

source scripts/success_message
