#!/bin/bash

set -o errexit

dataFiles="$1"
description="$2"
numIterations="$3"
debug="$4"
fsAlgos="$5"
outFeaturesFile="$6"
outBenchmarkFile="$7"

scripts/featureselection "$dataFiles" "$description" "$numIterations" "$debug" "$fsAlgos" "$outFeaturesFile" "$outBenchmarkFile" montecarlo 0
