#!/bin/bash

set -o errexit

dataFiles="$1"
description="$2"
numIterations="$3"
debug="$4"
fsAlgos="$5"
outFeaturesFile="$6"
outSummarizedFeaturesFile="$7"
outBenchmarkFile="$8"

scripts/featureselection "$dataFiles" "$description" "$numIterations" "$debug" "$fsAlgos" "$outFeaturesFile" "$outSummarizedFeaturesFile" "$outBenchmarkFile" montecarlo 0
