#!/bin/bash

set -euo pipefail

source scripts/shared_functions
source scripts/first_param_check

dataFiles="$(python scripts/ParseArgs.py --data TRUE $@)"
description="$(python scripts/ParseArgs.py --description TRUE $@)"
numIterations="$(python scripts/ParseArgs.py --iterations TRUE $@)"
verbose="$(python scripts/ParseArgs.py --verbose FALSE false $@)"
fsAlgos="$(python scripts/ParseArgs.py --fs-algo TRUE "$@")"
outputDir="$(python scripts/ParseArgs.py --output-dir TRUE $@)"
tmpDir="$(python scripts/ParseArgs.py --temp-dir FALSE '' $@)"

checkParamParseOutput "$dataFiles"
checkParamParseOutput "$description"
checkParamParseOutput "$numIterations"
checkParamParseOutput "$verbose"
checkParamParseOutput "$fsAlgos"
checkParamParseOutput "$outputDir"
checkParamParseOutput "$tmpDir"

mkdir -p $outputDir
outFeaturesFile="$outputDir/SelectedFeatures.tsv"
outSummarizedFeaturesFile="$outputDir/SelectedFeatures_Summarized.tsv"
outBenchmarkFile="$outputDir/ElapsedTime.tsv"
outLogFile="$outputDir/Log.txt"

tmpDir="$(getTempDir "$tmpDir")"

source scripts/print_args

function cleanup {
  rm -rf $tmpDir
}

cleanup

trap cleanup INT TERM EXIT

scripts/featureselection "$dataFiles" "$description" "$numIterations" "$verbose" "$fsAlgos" "$outFeaturesFile" "$outSummarizedFeaturesFile" "$outBenchmarkFile" montecarlo 0 $tmpDir 2>&1 | tee -a "$outLogFile"

cleanup

source scripts/success_message
