#!/bin/bash

set -euo pipefail

source scripts/shared_functions
source scripts/first_param_check

dataFiles="$1"
description="$2"
outerNumIterations="$3"
innerNumIterations="$4"
debug="$5"
classifAlgos="$6"
outPredictionsFile="$7"
outMetricsFile="$8"
outNestedPredictionsFile="${9}"
outNestedMetricsFile="${10}"
outNestedBenchmarkFile="${11}"
outLogFile="${12}"

if [[ "$outLogFile" == "" ]]
then
  echo An output log file must be specified.
  exit 1
fi

source scripts/print_args

scripts/nestedclassification "$dataFiles" "$description" "$outerNumIterations" "$innerNumIterations" "$debug" "$classifAlgos" "$outPredictionsFile" "$outMetricsFile" "$outNestedPredictionsFile" "$outNestedMetricsFile" "$outNestedBenchmarkFile" montecarlo 0 2>&1 | tee -a "$outLogFile"

source scripts/success_message
