#!/bin/bash

set -euo pipefail

source scripts/shared_functions
source scripts/first_param_check

dataFiles="$(python3 scripts/ParseArgs.py --data TRUE "$@")"
description="$(python3 scripts/ParseArgs.py --description TRUE $@)"
numIterations="$(python3 scripts/ParseArgs.py --iterations TRUE $@)"
outerNumFolds="$(python3 scripts/ParseArgs.py --outer-folds TRUE $@)"
innerNumFolds="$(python3 scripts/ParseArgs.py --inner-folds TRUE $@)"
classifAlgos="$(python3 scripts/ParseArgs.py --classif-algo TRUE "$@")"
numFeaturesOptions="$(python3 scripts/ParseArgs.py --num-features TRUE "$@")"
fsAlgos="$(python3 scripts/ParseArgs.py --fs-algo TRUE "$@")"
verbose="$(python3 scripts/ParseArgs.py --verbose FALSE false $@)"
ohe="$(python3 scripts/ParseArgs.py --ohe FALSE true $@)"
scale="$(python3 scripts/ParseArgs.py --scale FALSE none $@)"
impute="$(python3 scripts/ParseArgs.py --impute FALSE false $@)"
randomSeed="$(python3 scripts/ParseArgs.py --seed FALSE 0 $@)"
numCores="$(python3 scripts/ParseArgs.py --num-cores FALSE 1 $@)"
tmpDir="$(python3 scripts/ParseArgs.py --temp-dir FALSE '' $@)"

checkParamParseOutput "$dataFiles"
checkParamParseOutput "$description"
checkParamParseOutput "$numIterations"
checkParamParseOutput "$outerNumFolds"
checkParamParseOutput "$innerNumFolds"
checkParamParseOutput "$classifAlgos"
checkParamParseOutput "$numFeaturesOptions"
checkParamParseOutput "$fsAlgos"
checkParamParseOutput "$verbose"
checkParamParseOutput "$ohe"
checkParamParseOutput "$scale"
checkParamParseOutput "$impute"
checkParamParseOutput "$randomSeed"
checkParamParseOutput "$numCores"
checkParamParseOutput "$tmpDir"

dataFiles="$(modifyDataFilePaths "$dataFiles")"

outputDir=/OutputData
checkOutputDir $outputDir

outSelectedFeaturesFile="$outputDir/SelectedFeatures.tsv"
outPredictionsFile="$outputDir/Predictions.tsv"
outMetricsFile="$outputDir/Metrics.tsv"
outNestedSelectedFeaturesFile="$outputDir/Nested_SelectedFeatures.tsv"
outNestedSummarizedSelectedFeaturesFile="$outputDir/Nested_SelectedFeatures_Summarized.tsv"
outNestedPredictionsFile="$outputDir/Nested_Predictions.tsv"
outNestedMetricsFile="$outputDir/Nested_Metrics.tsv"
outNestedFeatureSelectionBenchmarkFile="$outputDir/Nested_FeatureSelection_ElapsedTime.tsv"
outNestedClassificationBenchmarkFile="$outputDir/Nested_Classification_ElapsedTime.tsv"
outNestedBestFile="$outputDir/Nested_Best.tsv"
outLogFile="$outputDir/Log.txt"

source scripts/print_args

function cleanup {
  rm -rf $tmpDir
}

cleanup
tmpDir="$(getTempDir "$tmpDir")"

trap cleanup INT TERM EXIT

validationType=crossvalidation
source scripts/setup

echo "Parsing data..." 2>&1 | timestamp | tee -a "$outLogFile"
analysisDataFile=$tmpDir/data.gz
java $(getJavaArgs) -jar shinylearner.jar RAW_DATA_FILES="$dataFiles" ANALYSIS_DATA_FILE="$analysisDataFile" DEBUG=$verbose IMPUTE=$impute TEMP_DIR=$tmpDir 2> /dev/null

if [[ "$impute" == "true" ]]
then
  echo "Imputing missing data (where applicable)..." 2>&1 | timestamp | tee -a "$outLogFile"
  Rscript --vanilla scripts/Impute.R "$analysisDataFile" $verbose 2>&1 | timestamp | tee -a "$outLogFile"
fi

if [[ "$scale" != "none" ]]
then
  echo "Scaling numerical data (where applicable)..." | timestamp | tee -a "$outLogFile"
  python3 scripts/Scale.py "$analysisDataFile" "$scale" $verbose 2>&1 | timestamp | tee -a "$outLogFile"
fi

if [[ "$ohe" == "true" ]]
then
  echo "One-hot encoding categorical data (where applicable)..." 2>&1 | timestamp | tee -a "$outLogFile"
  python3 scripts/OneHotEncode.py "$analysisDataFile" 2>&1 | timestamp | tee -a "$outLogFile"
fi

for iteration in $(seq 1 $numIterations)
do
  outDir=$tmpDir/$iteration
  mkdir -p $outDir

  if [[ "$outSelectedFeaturesFile" == "" ]]
  then
    outSelectedFeaturesFileIteration=
  else
    outSelectedFeaturesFileIteration=$outDir/outfs
  fi
  if [[ "$outPredictionsFile" == "" ]]
  then
    outPredictionsFileIteration=
  else
    outPredictionsFileIteration=$outDir/outpreds
  fi
  if [[ "$outMetricsFile" == "" ]]
  then
    outMetricsFileIteration=
  else
    outMetricsFileIteration=$outDir/outmetrics
  fi
  if [[ "$outNestedSelectedFeaturesFile" == "" ]]
  then
    outNestedSelectedFeaturesFileIteration=
  else
    outNestedSelectedFeaturesFileIteration=$outDir/outfsnested
  fi
  if [[ "$outNestedPredictionsFile" == "" ]]
  then
    outNestedPredictionsFileIteration=
  else
    outNestedPredictionsFileIteration=$outDir/outpredsnested
  fi
  if [[ "$outNestedMetricsFile" == "" ]]
  then
    outNestedMetricsFileIteration=
  else
    outNestedMetricsFileIteration=$outDir/outmetricsnested
  fi
  if [[ "$outNestedFeatureSelectionBenchmarkFile" == "" ]]
  then
    outNestedFeatureSelectionBenchmarkFileIteration=
  else
    outNestedFeatureSelectionBenchmarkFileIteration=$outDir/outbenchfsnested
  fi
  if [[ "$outNestedClassificationBenchmarkFile" == "" ]]
  then
    outNestedClassificationBenchmarkFileIteration=
  else
    outNestedClassificationBenchmarkFileIteration=$outDir/outbenchclnested
  fi

  outNestedBestFileIteration=$outDir/outnestedbest
  randomSeed2=$(($randomSeed + $iteration))

  echo | timestamp | tee -a "$outLogFile"
  echo "**************************************************************" | timestamp | tee -a "$outLogFile"
  echo "Beginning analysis for cross-validation fold ${iteration}" | timestamp | tee -a "$outLogFile"
  echo "**************************************************************" | timestamp | tee -a "$outLogFile"
  scripts/nestedboth "$analysisDataFile" "$description" "$outerNumFolds" "$innerNumFolds" "$verbose" "$fsAlgos" "$numFeaturesOptions" "$classifAlgos" "$outSelectedFeaturesFileIteration" "$outPredictionsFileIteration" "$outMetricsFileIteration" "$outNestedSelectedFeaturesFileIteration" "" "$outNestedPredictionsFileIteration" "$outNestedMetricsFileIteration" "$outNestedFeatureSelectionBenchmarkFileIteration" "$outNestedClassificationBenchmarkFileIteration" "$outNestedBestFileIteration" crossvalidation $randomSeed2 NA $impute $outDir "$outLogFile" "$numCores"
done

echo 2>&1 | timestamp | tee -a "$outLogFile"
echo "**************************************************************" | timestamp | tee -a "$outLogFile"
echo "Finalizing analysis" | timestamp | tee -a "$outLogFile"
echo "**************************************************************" | timestamp | tee -a "$outLogFile"
echo 2>&1 | timestamp | tee -a "$outLogFile"

echo "Combining results across cross-validation iterations..." | timestamp | tee -a "$outLogFile"
python3 scripts/CombineCrossValidationIterations.py "$tmpDir/*/outfs,$tmpDir/*/outpreds,$tmpDir/*/outmetrics,$tmpDir/*/outfsnested,$tmpDir/*/outpredsnested,$tmpDir/*/outmetricsnested,$tmpDir/*/outbenchfsnested,$tmpDir/*/outbenchclnested,$tmpDir/*/outnestedbest" "$tmpDir/outfs,$tmpDir/outpreds,$tmpDir/outmetrics,$tmpDir/outfsnested,$tmpDir/outpredsnested,$tmpDir/outmetricsnested,$tmpDir/outbenchfsnested,$tmpDir/outbenchclnested,$tmpDir/outnestedbest" 2>&1 | timestamp | tee -a "$outLogFile"

sortFile $tmpDir/outfs "-k1,1 -k2,2n -k3,3n -k4" "$outSelectedFeaturesFile" 2>&1 | timestamp | tee -a "$outLogFile"
sortFile $tmpDir/outpreds "-k1,1 -k2,2n -k3,3n -k4" "$outPredictionsFile" 2>&1 | timestamp | tee -a "$outLogFile"
sortFile $tmpDir/outmetrics "-k1,1 -k2,2n -k3,3n -k4" "$outMetricsFile" 2>&1 | timestamp | tee -a "$outLogFile"
sortFile $tmpDir/outfsnested "-k1,1 -k2,2n -k3,3n -k4,4n -k5" "$outNestedSelectedFeaturesFile" 2>&1 | timestamp | tee -a "$outLogFile"
sortFile $tmpDir/outpredsnested "-k1,1 -k2,2n -k3,3n -k4,4n -k5" "$outNestedPredictionsFile" 2>&1 | timestamp | tee -a "$outLogFile"
sortFile $tmpDir/outmetricsnested "-k1,1 -k2,2n -k3,3n -k4,4n -k5 -k6,6n -k7" "$outNestedMetricsFile" 2>&1 | timestamp | tee -a "$outLogFile"
sortFile $tmpDir/outbenchfsnested "-k1,1 -k2,2n -k3,3n -k4,4n -k5" "$outNestedFeatureSelectionBenchmarkFile" 2>&1 | timestamp | tee -a "$outLogFile"
sortFile $tmpDir/outbenchclnested "-k1,1 -k2,2n -k3,3n -k4,4n -k5,4n -k5 -k6,6n -k7" "$outNestedClassificationBenchmarkFile" 2>&1 | timestamp | tee -a "$outLogFile"
sortFile $tmpDir/outnestedbest "-k1,1 -k2,2n -k3,3n -k4,4n -k5,4n -k5 -k6,6n -k7" "$outNestedBestFile" 2>&1 | timestamp | tee -a "$outLogFile"

echo "Summarizing feature ranks..." 2>&1 | timestamp | tee -a "$outLogFile"
errFile=/dev/null
if [[ "$verbose" == "true" ]]
then
  errFile=$(mktemp $tmpDir/XXXXXXXXX)
fi
python scripts/BordaCountFeatures.py "$outNestedSelectedFeaturesFile" "$outNestedSummarizedSelectedFeaturesFile"
#Rscript --vanilla scripts/BordaCountFeatures.R "$outNestedSelectedFeaturesFile" "$outNestedSummarizedSelectedFeaturesFile" 2> $errFile | timestamp | tee -a "$outLogFile"
#printError $verbose $errFile

cleanup

source scripts/success_message
