#!/bin/bash

set -euo pipefail

source scripts/first_param_check

dataFiles="$1"
description="$2"
numIterations="$3"
outerNumFolds="$4"
innerNumFolds="$5"
debug="$6"
classifAlgos="$7"
outPredictionsFile="$8"
outMetricsFile="$9"
outNestedPredictionsFile="${10}"
outNestedMetricsFile="${11}"
outNestedBenchmarkFile="${12}"
outLogFile="${13}"

tmpDir=$(mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir')

function cleanup_cv {
  rm -rf $tmpDir
}

cleanup_cv

if [[ "$outLogFile" == "" ]]
then
  echo An output log file must be specified.
  exit 1
fi

source scripts/print_args

for iteration in $(seq 1 $numIterations)
do
  outDir=$tmpDir/$iteration
  mkdir -p $outDir

  if [[ "$outPredictionsFile" == "" ]]
  then
    outPredictionsFileIteration=
  else
    outPredictionsFileIteration=$outDir/outpreds
  fi
  if [[ "$outMetricsFile" == "" ]]
  then
    outMetricsFileIteration=
  else
    outMetricsFileIteration=$outDir/outmetrics
  fi
  if [[ "$outNestedPredictionsFile" == "" ]]
  then
    outNestedPredictionsFileIteration=
  else
    outNestedPredictionsFileIteration=$outDir/outpredsnested
  fi
  if [[ "$outNestedMetricsFile" == "" ]]
  then
    outNestedMetricsFileIteration=
  else
    outNestedMetricsFileIteration=$outDir/outmetricsnested
  fi
  if [[ "$outNestedBenchmarkFile" == "" ]]
  then
    outNestedBenchmarkFileIteration=
  else
    outNestedBenchmarkFileIteration=$outDir/outbenchnested
  fi

  echo
  echo "**************************************************************" | tee -a "$outLogFile"
  echo "Beginning analysis for cross-validation fold ${iteration}" | tee -a "$outLogFile"
  echo "**************************************************************" | tee -a "$outLogFile"
  scripts/nestedclassification "$dataFiles" "$description" "$outerNumFolds" "$innerNumFolds" "$debug" "$classifAlgos" "$outPredictionsFileIteration" "$outMetricsFileIteration" "$outNestedPredictionsFileIteration" "$outNestedMetricsFileIteration" "$outNestedBenchmarkFileIteration" crossvalidation $iteration 2>&1 | tee -a "$outLogFile"
done

echo
echo "**************************************************************" | tee -a "$outLogFile"
echo "Finalizing analysis" | tee -a "$outLogFile"
echo "**************************************************************" | tee -a "$outLogFile"
echo

echo "Combining results across cross-validation iterations..." | tee -a "$outLogFile"
python scripts/CombineCrossValidationIterations.py "$tmpDir/*/outpreds,$tmpDir/*/outmetrics,$tmpDir/*/outpredsnested,$tmpDir/*/outmetricsnested,$tmpDir/*/outbenchnested" "$tmpDir/outpreds,$tmpDir/outmetrics,$tmpDir/outnestedpreds,$tmpDir/outnestedmetrics,$tmpDir/outnestedbenchmark" 2>&1 | tee -a "$outLogFile"

source scripts/shared_functions
sortFile $tmpDir/outpreds "-k1,1 -k2,2n -k3,3n -k4" "$outPredictionsFile"
sortFile $tmpDir/outmetrics "-k1,1 -k2,2n -k3,3n -k4" "$outMetricsFile"
sortFile $tmpDir/outnestedpreds "-k1,1 -k2,2n -k3,3n -k4,4n -k5" "$outNestedPredictionsFile"
sortFile $tmpDir/outnestedmetrics "-k1,1 -k2,2n -k3,3n -k4,4n -k5" "$outNestedMetricsFile"
sortFile $tmpDir/outnestedbenchmark "-k1,1 -k2,2n -k3,3n -k4,4n -k5" "$outNestedBenchmarkFile"

cleanup_cv

source scripts/success_message
