#!/bin/bash

set -o errexit
set -o pipefail

dataFiles="$1"
description="$2"
numIterations="$3"
outerNumFolds="$4"
innerNumFolds="$5"
debug="$6"
fsAlgos="$7"
numFeaturesOptions="$8"
classifAlgos="$9"
outSelectedFeaturesFile="${10}"
outPredictionsFile="${11}"
outMetricsFile="${12}"
outNestedSelectedFeaturesFile="${13}"
outNestedSummarizedSelectedFeaturesFile="${14}"
outNestedPredictionsFile="${15}"
outNestedMetricsFile="${16}"
outNestedFeatureSelectionBenchmarkFile="${17}"
outNestedClassificationBenchmarkFile="${18}"
outLogFile="${19}"

tmpDir=$(mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir')

function cleanup {
  rm -rf $tmpDir
}

cleanup

if [[ "$outLogFile" == "" ]]
then
  echo An output log file must be specified.
  exit 1
fi

rm -f "$outLogFile"

for iteration in $(seq 1 $numIterations)
do
  outDir=$tmpDir/$iteration
  mkdir -p $outDir

  if [[ "$outSelectedFeaturesFile" == "" ]]
  then
    outSelectedFeaturesFileIteration=
  else
    outSelectedFeaturesFileIteration=$outDir/outfs
  fi
  if [[ "$outPredictionsFile" == "" ]]
  then
    outPredictionsFileIteration=
  else
    outPredictionsFileIteration=$outDir/outpreds
  fi
  if [[ "$outMetricsFile" == "" ]]
  then
    outMetricsFileIteration=
  else
    outMetricsFileIteration=$outDir/outmetrics
  fi
  if [[ "$outNestedSelectedFeaturesFile" == "" ]]
  then
    outNestedSelectedFeaturesFileIteration=
  else
    outNestedSelectedFeaturesFileIteration=$outDir/outfsnested
  fi
  if [[ "$outNestedPredictionsFile" == "" ]]
  then
    outNestedPredictionsFileIteration=
  else
    outNestedPredictionsFileIteration=$outDir/outpredsnested
  fi
  if [[ "$outNestedMetricsFile" == "" ]]
  then
    outNestedMetricsFileIteration=
  else
    outNestedMetricsFileIteration=$outDir/outmetricsnested
  fi
  if [[ "$outNestedFeatureSelectionBenchmarkFile" == "" ]]
  then
    outNestedFeatureSelectionBenchmarkFileIteration=
  else
    outNestedFeatureSelectionBenchmarkFileIteration=$outDir/outbenchfsnested
  fi
  if [[ "$outNestedClassificationBenchmarkFile" == "" ]]
  then
    outNestedClassificationBenchmarkFileIteration=
  else
    outNestedClassificationBenchmarkFileIteration=$outDir/outbenchclnested
  fi

  scripts/nestedboth "$dataFiles" "$description" "$outerNumFolds" "$innerNumFolds" "$debug" "$fsAlgos" "$numFeaturesOptions" "$classifAlgos" "$outSelectedFeaturesFileIteration" "$outPredictionsFileIteration" "$outMetricsFileIteration" "$outNestedSelectedFeaturesFileIteration" "" "$outNestedPredictionsFileIteration" "$outNestedMetricsFileIteration" "$outNestedFeatureSelectionBenchmarkFileIteration" "$outNestedClassificationBenchmarkFileIteration" crossvalidation $iteration 2>&1 | tee -a "$outLogFile"
done

python scripts/CombineCrossValidationIterations.py "$tmpDir/*/outfs,$tmpDir/*/outpreds,$tmpDir/*/outmetrics,$tmpDir/*/outfsnested,$tmpDir/*/outpredsnested,$tmpDir/*/outmetricsnested,$tmpDir/*/outbenchfsnested,$tmpDir/*/outbenchclnested" "$outSelectedFeaturesFile,$outPredictionsFile,$outMetricsFile,$outNestedSelectedFeaturesFile,$outNestedPredictionsFile,$outNestedMetricsFile,$outNestedFeatureSelectionBenchmarkFile,$outNestedClassificationBenchmarkFile" 2>&1 | tee -a "$outLogFile"

source scripts/helper
Rscript --vanilla scripts/BordaCountFeatures.R "$outNestedSelectedFeaturesFile" "$outNestedSummarizedSelectedFeaturesFile" 2> $errFile | tee -a "$outLogFile"
printError

cleanup

echo "Analysis successfully completed!" | tee -a "$outLogFile"
