#!/bin/bash

set -euo pipefail

source scripts/shared_functions
source scripts/first_param_check

dataFiles="$(python scripts/ParseArgs.py --data TRUE $@)"
description="$(python scripts/ParseArgs.py --description TRUE $@)"
outerNumIterations="$(python scripts/ParseArgs.py --outer-iterations TRUE $@)"
innerNumIterations="$(python scripts/ParseArgs.py --inner-iterations TRUE $@)"
verbose="$(python scripts/ParseArgs.py --verbose FALSE false $@)"
classifAlgos="$(python scripts/ParseArgs.py --classif-algo TRUE "$@")"
numFeaturesOptions="$(python scripts/ParseArgs.py --num-features TRUE "$@")"
fsAlgos="$(python scripts/ParseArgs.py --fs-algo TRUE "$@")"
outputDir="$(python scripts/ParseArgs.py --output-dir TRUE $@)"
tmpDir="$(python scripts/ParseArgs.py --temp-dir FALSE '' $@)"

checkParamParseOutput "$dataFiles"
checkParamParseOutput "$description"
checkParamParseOutput "$outerNumIterations"
checkParamParseOutput "$innerNumIterations"
checkParamParseOutput "$verbose"
checkParamParseOutput "$classifAlgos"
checkParamParseOutput "$numFeaturesOptions"
checkParamParseOutput "$fsAlgos"
checkParamParseOutput "$outputDir"
checkParamParseOutput "$tmpDir"

mkdir -p $outputDir
outSelectedFeaturesFile="$outputDir/SelectedFeatures.tsv"
outPredictionsFile="$outputDir/Predictions.tsv"
outMetricsFile="$outputDir/Metrics.tsv"
outNestedSelectedFeaturesFile="$outputDir/Nested_SelectedFeatures.tsv"
outNestedSummarizedSelectedFeaturesFile="$outputDir/Nested_SelectedFeatures_Summarized.tsv"
outNestedPredictionsFile="$outputDir/Nested_Predictions.tsv"
outNestedMetricsFile="$outputDir/Nested_Metrics.tsv"
outNestedFeatureSelectionBenchmarkFile="$outputDir/Nested_FeatureSelection_ElapsedTime.tsv"
outNestedClassificationBenchmarkFile="$outputDir/Nested_Classification_ElapsedTime.tsv"
outLogFile="$outputDir/Log.txt"

source scripts/print_args

function cleanup {
  rm -rf $tmpDir
}

cleanup
tmpDir="$(getTempDir "$tmpDir")"

trap cleanup INT TERM EXIT

scripts/nestedboth "$dataFiles" "$description" "$outerNumIterations" "$innerNumIterations" "$verbose" "$fsAlgos" "$numFeaturesOptions" "$classifAlgos" "$outSelectedFeaturesFile" "$outPredictionsFile" "$outMetricsFile" "$outNestedSelectedFeaturesFile" "$outNestedSummarizedSelectedFeaturesFile" "$outNestedPredictionsFile" "$outNestedMetricsFile" "$outNestedFeatureSelectionBenchmarkFile" "$outNestedClassificationBenchmarkFile" montecarlo 0 "$tmpDir" 2>&1 | tee -a "$outLogFile"

cleanup

source scripts/success_message
