#!/bin/bash

set -euo pipefail

source scripts/shared_functions
source scripts/first_param_check

dataFiles="$(python scripts/ParseArgs.py --data TRUE "$@")"
description="$(python scripts/ParseArgs.py --description TRUE $@)"
outerNumIterations="$(python scripts/ParseArgs.py --outer-iterations TRUE $@)"
innerNumIterations="$(python scripts/ParseArgs.py --inner-iterations TRUE $@)"
classifAlgos="$(python scripts/ParseArgs.py --classif-algo TRUE "$@")"
numFeaturesOptions="$(python scripts/ParseArgs.py --num-features TRUE "$@")"
fsAlgos="$(python scripts/ParseArgs.py --fs-algo TRUE "$@")"
outputDir="$(python scripts/ParseArgs.py --output-dir TRUE $@)"
verbose="$(python scripts/ParseArgs.py --verbose FALSE false $@)"
randomSeed="$(python scripts/ParseArgs.py --seed FALSE 1 $@)"
ohe="$(python scripts/ParseArgs.py --ohe FALSE true $@)"
tmpDir="$(python scripts/ParseArgs.py --temp-dir FALSE '' $@)"

checkParamParseOutput "$dataFiles"
checkParamParseOutput "$description"
checkParamParseOutput "$outerNumIterations"
checkParamParseOutput "$innerNumIterations"
checkParamParseOutput "$classifAlgos"
checkParamParseOutput "$numFeaturesOptions"
checkParamParseOutput "$fsAlgos"
checkParamParseOutput "$outputDir"
checkParamParseOutput "$verbose"
checkParamParseOutput "$ohe"
checkParamParseOutput "$tmpDir"

mkdir -p $outputDir
outSelectedFeaturesFile="$outputDir/SelectedFeatures.tsv"
outPredictionsFile="$outputDir/Predictions.tsv"
outMetricsFile="$outputDir/Metrics.tsv"
outNestedSelectedFeaturesFile="$outputDir/Nested_SelectedFeatures.tsv"
outNestedSummarizedSelectedFeaturesFile="$outputDir/Nested_SelectedFeatures_Summarized.tsv"
outNestedPredictionsFile="$outputDir/Nested_Predictions.tsv"
outNestedMetricsFile="$outputDir/Nested_Metrics.tsv"
outNestedFeatureSelectionBenchmarkFile="$outputDir/Nested_FeatureSelection_ElapsedTime.tsv"
outNestedClassificationBenchmarkFile="$outputDir/Nested_Classification_ElapsedTime.tsv"
outLogFile="$outputDir/Log.txt"

source scripts/print_args

function cleanup {
  rm -rf $tmpDir
}

cleanup
tmpDir="$(getTempDir "$tmpDir")"

trap cleanup INT TERM EXIT

validationType=montecarlo
source scripts/setup

echo "Parsing data..."
analysisDataFile=$tmpDir/data.gz
java -Xmx${mem} -jar shinylearner.jar RAW_DATA_FILES="$dataFiles" ANALYSIS_DATA_FILE="$analysisDataFile" DEBUG=$verbose TEMP_DIR=$tmpDir 2>&1 | tee -a "$outLogFile"

if [[ "$ohe" == "true" ]]
then
  echo "One-hot encoding categorical data (where applicable)..."
  python scripts/OneHotEncode.py "$analysisDataFile"
fi

scripts/nestedboth "$analysisDataFile" "$description" "$outerNumIterations" "$innerNumIterations" "$verbose" "$fsAlgos" "$numFeaturesOptions" "$classifAlgos" "$outSelectedFeaturesFile" "$outPredictionsFile" "$outMetricsFile" "$outNestedSelectedFeaturesFile" "$outNestedSummarizedSelectedFeaturesFile" "$outNestedPredictionsFile" "$outNestedMetricsFile" "$outNestedFeatureSelectionBenchmarkFile" "$outNestedClassificationBenchmarkFile" montecarlo $randomSeed $ohe "$tmpDir" 2>&1 | tee -a "$outLogFile"

cleanup

source scripts/success_message
