#!/bin/bash

set -euo pipefail

#######################################################################################
# This algorithm is implemented in the mlr software package (http://mlr-org.github.io).
#######################################################################################

trainingFilePath="$1"
testFilePath="$2"
classOptions="$3"

Rscript --vanilla AlgorithmScripts/Helper/mlr_c_generic.R "$trainingFilePath" "$testFilePath" "$classOptions" "multinom" 2>&1 | python AlgorithmScripts/Helper/ReformatMlrClassificationOutput.py "$classOptions"
