#!/bin/bash

set -euo pipefail

currentDir=$(pwd)

scripts/build
tar -zcf ShinyLearner.tar.gz shinylearner.jar scripts AlgorithmScripts README.md VERSION BuildTests BuildTestExpectedOutput LICENSE UserScripts

tmpDir=/tmp/build_local_docker

mkdir -p $tmpDir
rm -rf $tmpDir/*

mv ShinyLearner.tar.gz $tmpDir/
cp Dockerfile $tmpDir/
cp -r Validation $tmpDir/
cp -r BuildTests $tmpDir/

cd $tmpDir
sudo docker build -t srp33/shinylearner:test ./

mkdir input output
cp Validation/*.gz input/

sudo docker run --rm --name inputdata -v $(pwd)/input:/input -v $(pwd)/output:/output srp33/shinylearner:test /BuildTests/all
python BuildTests/CheckLogFiles.py "output/log.overall" 1
echo "All tests passed!!!"

cd $currentDir
rm -rf $tmpDir

#docker rmi $(docker images --format '{{.Repository}}' | grep 'srp33/shinylearner:test')
