#!/bin/bash

message="$1"

if [[ "$message" == "" ]]
then
  echo "No commit message was provided."
  exit 1
fi

cd AlgorithmScripts/Helper
./build_algorithm_scripts
cd ../..

python scripts/UpdateVersion.py travis.yml.template VERSION .travis.yml
python scripts/UpdateVersion.py README_template.md VERSION README.md

git add .travis.yml
git add --all .
git commit -m "$message"
git push origin master
