#!/bin/bash

set -o errexit

message="$1"

if [[ "$message" == "" ]]
then
  echo "No commit message was provided."
  exit 1
fi

cd AlgorithmScripts/Helper
./build_algorithm_scripts
cd ../..

python scripts/UpdateVersion.py travis.yml.template VERSION True .travis.yml
python scripts/UpdateVersion.py README_template.md VERSION False README.md
python scripts/UpdateVersion.py GettingStarted_template.md VERSION False GettingStarted.md

./scripts/build_image shinylearner
./BuildTests/all

git add .travis.yml
git add --all .
git commit -m "$message"
git push origin master

cd ../ShinyLearner_gpu

./commit "$message"
