#!/bin/bash

set -euo pipefail

#####################################################
# This algorithm is implemented in the scikit-learn
# software package (http://scikit-learn.org/stable/).
#####################################################

dataFilePath="$1"
numCores="$2"

export JOBLIB_START_METHOD="forkserver"

python3 AlgorithmScripts/Helper/sklearn_f_generic.py "$dataFilePath" "$numCores" "coef" "scorer = RandomizedLogisticRegression(C=1, scaling=0.5, sample_fraction=0.75, n_resampling=200, selection_threshold=0.25, tol=0.001, fit_intercept=True, verbose=False, normalize=True, random_state=R_SEED)" 2>&1 | python3 AlgorithmScripts/Helper/ReformatSklearnOutput.py
