#!/bin/bash

##########################################################
# This algorithm is implemented in the weka
# software package (http://www.cs.waikato.ac.nz/ml/weka/).
##########################################################

bash "$(dirname $0)"/../../../../Helper/weka_c_generic "$1" "$2" "$3" "weka.classifiers.bayes.NaiveBayes"
