#!/bin/bash

#currentDir=$(pwd)
#rm -rf shinylearnerweb/ShinyLearner
#mkdir shinylearnerweb/ShinyLearner
#cd /tmp
#rm -rf ShinyLearner
#git clone https://github.com/srp33/ShinyLearner.git 
#mv ShinyLearner/AlgorithmScripts $currentDir/shinylearnerweb/ShinyLearner/
#rm -rf ShinyLearner
#cd $currentDir

#sudo docker build -t shinylearnerweb .
sudo docker tag shinylearnerweb srp33/shinylearnerweb:v1

#sudo docker login
sudo docker push srp33/shinylearnerweb:v1
