#!/bin/bash

set -o errexit

server=lspiccolo.byu.edu
serverTempDir=/tmp/shinylearner_srv
serverShinyDir=/srv/shiny-server/shinylearner

# Server config
ssh $server "mkdir -pv $serverTempDir"
ssh $server "rm -rfv $serverTempDir/*"
rsync -av server_config/shiny-server.conf $server:$serverTempDir/
ssh -t $server "sudo cp -v $serverTempDir/shiny-server.conf /etc/shiny-server/"

# Copy Shiny files
ssh -t $server "sudo mkdir -p $serverShinyDir"
ssh -t $server "sudo rm -rfv $serverShinyDir/*"
rsync -av server.R $server:$serverTempDir
rsync -av ui.R $server:$serverTempDir
rsync -av www $server:$serverTempDir
ssh -t $server "sudo cp -v $serverTempDir/server.R $serverShinyDir"
ssh -t $server "sudo cp -v $serverTempDir/ui.R $serverShinyDir"
ssh -t $server "sudo cp -rv $serverTempDir/www $serverShinyDir"

# Get latest algorithm scripts
ssh $server "cd /tmp; rm -rf ShinyLearner; git clone https://github.com/srp33/ShinyLearner.git"
ssh -t $server "sudo cp -rv /tmp/ShinyLearner/AlgorithmScripts $serverShinyDir/ShinyLearner/"
ssh $server "rm -rf /tmp/ShinyLearner"

# Remove temp files
ssh $server "rm -rfv $serverTempDir"
