#!/bin/bash

set -o errexit
set -o pipefail

bash "$(dirname $0)"/../../../../Helper/weka_fs_generic "$1" 'weka.attributeSelection.OneRAttributeEval -S 1 -F 10 -B 6 -s "weka.attributeSelection.Ranker -T -1.7976931348623157E308 -N -1"'
