#!/bin/bash

set -euo pipefail

#####################################################
# This algorithm is implemented in the scikit-learn
# software package (http://scikit-learn.org/stable/).
#####################################################

dataFilePath="$1"

python AlgorithmScripts/Helper/sklearn_f_generic.py "$dataFilePath" "rfe" "from sklearn.svm import SVC; from sklearn.feature_selection import RFE; estimator = SVC(random_state=R_SEED, kernel='linear')" 2>&1 | python AlgorithmScripts/Helper/ReformatSklearnOutput.py
