#!/bin/bash

set -euo pipefail

#####################################################
# This algorithm is implemented in the scikit-learn
# software package (http://scikit-learn.org/stable/).
#####################################################

dataFilePath="$1"

python AlgorithmScripts/Helper/sklearn_f_generic.py "$dataFilePath" "rfe" "selector = RFE(SVC(random_state=R_SEED, kernel='linear'), n_features_to_select=1, step=0.1)" 2>&1 | python AlgorithmScripts/Helper/ReformatSklearnOutput.py
