#!/bin/bash

mlflexDirPath="$1"
dataFilePath="$2"

parameters='weka.attributeSelection.OneRAttributeEval -S 1 -F 10 -B 6 -s "weka.attributeSelection.Ranker -T -1.7976931348623157E308 -N -1"'

classPath=""

sh "$(dirname $0)"/Helper/weka_fs_generic "$mlflexDirPath" "$classPath" "$dataFilePath" "$parameters"
