#!/bin/bash

mlflexDirPath="$1"
dataFilePath="$2"

parameters='weka.attributeSelection.SVMAttributeEval -X 1 -Y 0 -Z 0 -P 1.0E-25 -T 1.0E-10 -C 1.0 -N 2 -s "weka.attributeSelection.Ranker -T -1.7976931348623157E308 -N -1"'

classPath="$mlflexDirPath/lib/SVMAttributeEval.jar"

sh "$(dirname $0)"/Helper/weka_fs_generic "$mlflexDirPath" "$classPath" "$dataFilePath" "$parameters"
