#!/bin/bash

set -euo pipefail

trainingFilePath="$1"
testFilePath="$2"
classOptions="$3"
numCores="$4"
verbose="$5"


#######################################################
# Args:
# 1 - Training File
# 2 - Test File
# 3 - Class Options
# 4 - Number of CPU cores
# 5 - Verbosity
# 6 - Model Type (SNN)
# 7 - layers (16,16,etc...)
# 8 - Dropout (0.0-1.0)
# 9 - Regularization (0.0-1.0)
# 10 - Batch Normalization (false for snn)
# 11 - Number of epochs
#######################################################


python3 AlgorithmScripts/Classification/tsv/keras/dnn/dnn.py "$trainingFilePath" "$testFilePath" "$classOptions" "$numCores" "$verbose" \
"snn" 16,16 "0.2" "0.1" "false" "100"
