#!/bin/bash

set -euo pipefail

#######################################################################################
# This algorithm is implemented in the mlr software package (http://mlr-org.github.io).
#######################################################################################

dataFilePath="$1"

Rscript --max-ppsize=500000 --vanilla AlgorithmScripts/Helper/mlr_f_generic.R "$dataFilePath" "randomForestSRC.rfsrc" 2>&1 | python AlgorithmScripts/Helper/ReformatMlrFeatureSelectionOutput.py
