#!/bin/bash

#######################################################################################
# This algorithm is implemented in the mlr software package (http://mlr-org.github.io).
#######################################################################################

bash "$(dirname $0)"/../../../../Helper/mlr_fs_generic "$1" "$0"
