#!/bin/bash

#####################################################
# This algorithm is implemented in the scikit-learn
# software package (http://scikit-learn.org/stable/).
#####################################################

bash $(dirname $0)/../../../../Helper/sklearn_c_generic "$1" "$2" "$3" $0
