#!/bin/bash

dataFilePath="$1"
callingScript="$2"

dirName=$(dirname $0)
algorithmAbbreviated=$(python $dirName/ParseAlgorithmName.py $callingScript)

#python $dirName/sklearn_fs_generic.py "$dataFilePath" "$algorithmAbbreviated"
python $dirName/sklearn_fs_generic.py "$dataFilePath" "$algorithmAbbreviated" 2>&1 | python $dirName/ReformatSklearnOutput.py
