#!/bin/bash

set -euo pipefail

validationType=$1

if [[ "$validationType" == "" ]]
then
  echo No validation type was specified. This may not be the script you want to be executing.
  exit 1
fi

./scripts/build

currentDir=$(pwd)
testDir=/tmp/ML_Flex_Lite_Test_FS
outputDir=$currentDir/TestOutput/featureselection

rm -rf $testDir
mkdir -p $testDir

cp -r shinylearner.jar $testDir/
mkdir $testDir/lib
cp -r lib/* $testDir/lib/
cp -r scripts $testDir/
cp -r AlgorithmScripts $testDir/
cp -r UserScripts $testDir/
cp -r VERSION $testDir/

mkdir -p $outputDir
rm -f $outputDir/${validationType}*

cd $testDir

validation=StrongSignal_Both
dataFile=$currentDir/Validation/${validation}.tsv.gz
fsAlgo=AlgorithmScripts/FeatureSelection/tsv/sklearn/random_logistic_regression/default
#debug=true
debug=false
outFeaturesFile=$outputDir/${validationType}_${validation}_SelectedFeatures.tsv
outSummarizedFeaturesFile=$outputDir/${validationType}_${validation}_SelectedFeatures_Summarized.tsv
outBenchmarkFile=$outputDir/${validationType}_${validation}_Benchmark.tsv
outLogFile=$outputDir/${validationType}_${validation}.log

if [[ "$validationType" == "montecarlo" ]]
then
  UserScripts/featureselection_${validationType} "$dataFile" "$validation" 2 $debug "$fsAlgo" "$outFeaturesFile" "$outSummarizedFeaturesFile" "$outBenchmarkFile" "$outLogFile"
else
  UserScripts/featureselection_${validationType} "$dataFile" "$validation" 2 2 $debug "$fsAlgo" "$outFeaturesFile" "$outSummarizedFeaturesFile" "$outBenchmarkFile" "$outLogFile"
fi
