#!/bin/bash

set -euo pipefail

validationType=$1

if [[ "$validationType" == "" ]]
then
  echo No validation type was specified. This may not be the script you want to be executing.
  exit 1
fi

./scripts/build

currentDir=$(pwd)
testDir=/tmp/ML_Flex_Lite_Test_NestedBoth
outputDir=$currentDir/TestOutput/nestedboth

rm -rf $testDir
mkdir -p $testDir

cp -r shinylearner.jar $testDir/
mkdir $testDir/lib
cp -r lib/* $testDir/lib/
cp -r scripts $testDir/
cp -r AlgorithmScripts $testDir/
cp -r UserScripts $testDir/

mkdir -p $outputDir
rm -f $outputDir/${validationType}*

cd $testDir

validation=StrongSignal_Both
dataFile=$currentDir/Validation/${validation}.tsv.gz
fsAlgo="AlgorithmScripts/FeatureSelection/tsv/sklearn/r*/default"
numFeaturesOptions="5,20"
classifAlgo="AlgorithmScripts/Classification/tsv/sklearn/l*/default"
#debug=true
debug=false

if [[ "$validationType" == "montecarlo" ]]
then
  UserScripts/nestedboth_${validationType} "$dataFile" $validation 2 2 $debug "$fsAlgo" "$numFeaturesOptions" "$classifAlgo" $outputDir/${validationType}_${validation}_SelectedFeatures.tsv $outputDir/${validationType}_${validation}_Predictions.tsv $outputDir/${validationType}_${validation}_Metrics.tsv $outputDir/${validationType}_${validation}_SelectedFeatures_Nested.tsv $outputDir/${validationType}_${validation}_SelectedFeatures_Summarized_Nested.tsv $outputDir/${validationType}_${validation}_Predictions_Nested.tsv $outputDir/${validationType}_${validation}_Metrics_Nested.tsv $outputDir/${validationType}_${validation}_Benchmark_FeatureSelection_Nested.tsv $outputDir/${validationType}_${validation}_Benchmark_Classification_Nested.tsv $outputDir/${validationType}_${validation}.log
else
  UserScripts/nestedboth_${validationType} "$dataFile" $validation 2 2 2 $debug "$fsAlgo" "$numFeaturesOptions" "$classifAlgo" $outputDir/${validationType}_${validation}_SelectedFeatures.tsv $outputDir/${validationType}_${validation}_Predictions.tsv $outputDir/${validationType}_${validation}_Metrics.tsv $outputDir/${validationType}_${validation}_SelectedFeatures_Nested.tsv $outputDir/${validationType}_${validation}_SelectedFeatures_Summarized_Nested.tsv $outputDir/${validationType}_${validation}_Predictions_Nested.tsv $outputDir/${validationType}_${validation}_Metrics_Nested.tsv $outputDir/${validationType}_${validation}_Benchmark_FeatureSelection_Nested.tsv $outputDir/${validationType}_${validation}_Benchmark_Classification_Nested.tsv $outputDir/${validationType}_${validation}.log
fi
