#!/bin/bash

set -euo pipefail

validationType=$1

if [[ "$validationType" == "" ]]
then
  echo No validation type was specified. This may not be the script you want to be executing.
  exit 1
fi

./scripts/build

currentDir=$(pwd)
testDir=/tmp/ML_Flex_Lite_Test_NestedCL
outputDir=$currentDir/TestOutput/nestedclassification

rm -rf $testDir
mkdir -p $testDir

cp -r shinylearner.jar $testDir/
mkdir $testDir/lib
cp -r lib/* $testDir/lib/
cp -r scripts $testDir/
cp -r AlgorithmScripts $testDir/
cp -r UserScripts $testDir/

mkdir -p $outputDir
rm -f $outputDir/${validationType}*

cd $testDir

validation=StrongSignal_Both
#dataFile=$currentDir/Validation/${validation}.tsv.gz
#dataFile="$currentDir/debug_data/*.tsv.gz"
dataFile="$currentDir/debug_data/Archive/mrna-sc_stad.tsv.gz,$currentDir/debug_data/stad_cv_surv1_stad.tsv.gz"
#classifAlgo="$currentDir/AlgorithmScripts/Classification/tsv/sklearn/l*/default"
classifAlgo="$currentDir/AlgorithmScripts/Classification/tsv/sklearn/knn/default"
#debug=true
debug=false

if [[ "$validationType" == "montecarlo" ]]
then
  UserScripts/nestedclassification_${validationType} "$dataFile" $validation 2 2 $debug "$classifAlgo" $outputDir/${validationType}_${validation}_Predictions.tsv $outputDir/${validationType}_${validation}_Metrics.tsv $outputDir/${validationType}_${validation}_Predictions_Nested.tsv $outputDir/${validationType}_${validation}_Metrics_Nested.tsv $outputDir/${validationType}_${validation}_Benchmark_Nested.tsv $outputDir/${validationType}_${validation}.log
else
  UserScripts/nestedclassification_${validationType} "$dataFile" $validation 2 2 2 $debug "$classifAlgo" $outputDir/${validationType}_${validation}_Predictions.tsv $outputDir/${validationType}_${validation}_Metrics.tsv $outputDir/${validationType}_${validation}_Predictions_Nested.tsv $outputDir/${validationType}_${validation}_Metrics_Nested.tsv $outputDir/${validationType}_${validation}_Benchmark_Nested.tsv $outputDir/${validationType}_${validation}.log
fi
