#!/bin/bash

##########################################################
# This algorithm is implemented in the weka
# software package (http://www.cs.waikato.ac.nz/ml/weka/).
##########################################################

bash "$(dirname $0)"/../../../../Helper/weka_fs_generic "$1" 'weka.attributeSelection.SVMAttributeEval -X 1 -Y 0 -Z 0 -P 1.0E-25 -T 1.0E-10 -C 1.0 -N 2 -s "weka.attributeSelection.Ranker -T -1.7976931348623157E308 -N -1"'
