#! /bin/bash

this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
main_dir=$this_dir/../../../

VERSION=$(cat $main_dir/VERSION)

for template_file in $this_dir/docs/*
do
  out_file=$this_dir/../$(basename $template_file)

  echo Building docs for $out_file
  python3 BuildDoc.py $template_file $this_dir $out_file
done
