#!/bin/bash

mlflexDirPath="$1"
classPath="$2"
dataFilePath="$3"
parameters="$4"

classPath="$mlflexDirPath:$mlflexDirPath/lib/weka.jar:$classPath"

mem=$(top -l 1 | awk '/PhysMem:/ {print $2}' | tr '[:upper:]' '[:lower:]')
 
echo java -Xmx${mem} -classpath $classPath $parameters -i $dataFilePath | python $(dirname $0)/ReformatWekaParameters.py | sh | python $(dirname $0)/ParseWekaResults.py
#echo java -Xmx${mem} -classpath $classPath $parameters -i $dataFilePath
