#!/bin/bash

##########################################################
# This algorithm is implemented in the weka
# software package (http://www.cs.waikato.ac.nz/ml/weka/).
##########################################################

bash AlgorithmScripts/Helper/weka_fw_generic "$1" 'weka.classifiers.misc.VFI -- -B 0.6'
