#!/bin/bash

set -o errexit

description=StrongSignal_Both
classifAlgo=$currentDir/AlgorithmScripts/Classification/tsv/sklearn__functions__svm_linear
useDefaultParameters=true
debug=false

/BuildTests/helper nestedclassification montecarlo /Validation/${description}_Both.tsv.gz $description "$classifAlgo" $useDefaultParameters $debug
