#!/bin/bash

set -o errexit

inputDir=/input
outputDir=/output
classifAlgo="/AlgorithmScripts/Classification/tsv/sklearn/*/default"
debug=false

for description in StrongSignal_Both
do
  dataFile=$inputDir/${description}.tsv.gz

  rm -fv $outputDir/*
  /UserScripts/nestedclassification_montecarlo "$dataFile" $description 2 2 $debug "$classifAlgo" $outputDir/Predictions.tsv $outputDir/Metrics.tsv $outputDir/Benchmark.tsv $outputDir/Nested_Predictions.tsv $outputDir/Nested_Metrics.tsv $outputDir/Nested_Benchmark.tsv
  /BuildTests/check $description "$classifAlgo"
  rm -v $outputDir/*
done
