#!/bin/bash

set -euo pipefail

description="$1"
validationType="$2"
iterationsFolds="$3"
classifAlgo="$4"
inputDir="$5"
outputDir="$6"
verbose="$7"
logFile="$8"

analysisType=$(basename $0)
dataFile="$inputDir/$description.tsv.gz"
specificOutputDir=$outputDir/${analysisType}_${description}_${validationType}

UserScripts/${analysisType}_${validationType} --data "$dataFile" --description "$description" $iterationsFolds --classif-algo "$classifAlgo" --output-dir $specificOutputDir $verbose

python BuildTests/CheckAccuracy.py $analysisType $validationType $description "$classifAlgo" ${specificOutputDir}/Metrics.tsv Algorithm 2>&1 | tee -a $logFile
