#!/bin/bash

set -euo pipefail

description=$1
validationType=$2
classifAlgo="$3"
inputDir=$4
outputDir=$5
debug=$6
numOuterIterations=$7
numInnerIterations=$8
outLogFile=$9

source $(dirname $0)/helper

outPrefix=$outputDir/$(basename $0)_${description}_${validationType}

UserScripts/classification_${validationType} "$dataFile" $description $numCVIterations $numOuterIterations $debug "$classifAlgo" ${outPrefix}_Predictions.tsv ${outPrefix}_Metrics.tsv /dev/null $outLogFile
python BuildTests/CheckAccuracy.py classification $validationType $description "$classifAlgo" "${outPrefix}_Metrics.tsv" Algorithm 2>&1 | tee -a $outLogFile
