#!/bin/bash

set -euo pipefail

version="$1"
description="$2"
validationType="$3"
iterationsFolds="$4"
fsAlgo="$5"
verbose="$6"
logFile="$7"

inputDir=input
outputDir=output
logFile=$outputDir/$logFile

analysisType=$(basename $0)
dataFile="$inputDir/$description.tsv.gz"
specificOutputDir=$outputDir/${analysisType}_${description}_${validationType}

bash run_docker_command $version "UserScripts/${analysisType}_${validationType} --data \"$dataFile\" --description \"$description\" $iterationsFolds --fs-algo \"$fsAlgo\" --output-dir $specificOutputDir $verbose --impute true --ohe true" 2>&1 | tee -a $logFile

expectedNumAlgorithms=$(bash run_docker_command $version "ls $fsAlgo | wc -l")
python3 CheckSelectedFeatures.py $analysisType $validationType $description "$specificOutputDir/SelectedFeatures.tsv" Algorithm False $expectedNumAlgorithms 2>&1 | tee -a $logFile
python3 CheckSummarizedSelectedFeatures.py "$specificOutputDir/SelectedFeatures_Summarized.tsv" 2>&1 | tee -a $logFile
