#!/bin/bash

set -o errexit

function getNumCVIterations {
  numCVIterations=

  if [[ "$1" == "crossvalidation" ]]
  then
    numCVIterations=2
  fi

  echo $numCVIterations
}

dataFile=$inputDir/${description}.tsv.gz
numCVIterations=$(getNumCVIterations $validationType)
