#!/bin/bash

set -o errexit

analysisType=$1
validationType=$2
dataFile=$3
description=$4
classifAlgo=$5
debug=$6
outputDir=$7

mkdir -p $outputDir

if [[ "$validationType" == "montecarlo" ]]
then
  /UserScripts/${analysisType}_${validationType} "$dataFile" $description 2 2 $debug "$classifAlgo" $outputDir/Predictions.tsv $outputDir/Metrics.tsv $outputDir/Benchmark.tsv $outputDir/Nested_Predictions.tsv $outputDir/Nested_Metrics.tsv $outputDir/Nested_Benchmark.tsv
else
  /UserScripts/${analysisType}_${validationType} "$dataFile" $description 2 2 2 $debug "$classifAlgo" $outputDir/Predictions.tsv $outputDir/Metrics.tsv $outputDir/Benchmark.tsv $outputDir/Nested_Predictions.tsv $outputDir/Nested_Metrics.tsv $outputDir/Nested_Benchmark.tsv
fi
