#!/bin/bash

set -euo pipefail

version="$1"
description="$2"
validationType="$3"
iterationsFolds="$4"
fsAlgo="$5"
numFeaturesOptions="$6"
classifAlgo="$7"
verbose="$8"
logFile="$9"

inputDir=input
outputDir=output
logFile=$outputDir/$logFile

analysisType=$(basename $0)
dataFile="$inputDir/$description.tsv.gz"
specificOutputDir=$outputDir/${analysisType}_${description}_${validationType}

bash run_docker_command $version "UserScripts/${analysisType}_${validationType} --data \"$dataFile\" --description "$description" $iterationsFolds --fs-algo \"$fsAlgo\" --num-features \"$numFeaturesOptions\" --classif-algo \"$classifAlgo\" --output-dir $specificOutputDir $verbose"

# Should only be the ensemble algorithm
expectedNumAlgorithms=$(bash run_docker_command $version "ls $classifAlgo | wc -l")
python CheckAccuracy.py $analysisType $validationType $description "$specificOutputDir/Metrics.tsv" Algorithm $expectedNumAlgorithms 0 2>&1 | tee -a $logFile

# Testing the nested selected features not necessary, as long as outer folds work fine
#python CheckSelectedFeatures.py $analysisType $validationType $description "$fsAlgo" "$specificOutputDir/Nested_SelectedFeatures.tsv" Algorithm False 2>&1 | tee -a $logFile
python CheckSummarizedSelectedFeatures.py "$specificOutputDir/Nested_SelectedFeatures_Summarized.tsv" 2>&1 | tee -a $logFile

# Should only be the ensemble algorithm
python CheckSelectedFeatures.py $analysisType $validationType $description "$specificOutputDir/SelectedFeatures.tsv" Algorithm True 1 2>&1 | tee -a $logFile
