#!/bin/bash

set -o errexit

dataFile=$1
description=$2
classifAlgo=$3
debug=$4
outputDir=$5

mkdir -p $outputDir

/UserScripts/nestedclassification_montecarlo "$dataFile" $description 2 2 $debug "$classifAlgo" $outputDir/Predictions.tsv $outputDir/Metrics.tsv $outputDir/Benchmark.tsv $outputDir/Nested_Predictions.tsv $outputDir/Nested_Metrics.tsv $outputDir/Nested_Benchmark.tsv
