#!/bin/bash

imageName="$1"
version="$2"
cmd="$3"

docker run --rm -v $(pwd)/input:/input -v $(pwd)/output:/output srp33/${imageName}:version${version} bash -c "$cmd"

#sudo docker run --rm --name inputdata -v $(pwd)/input:/input -v $(pwd)/output:/output srp33/${imageName}:version${version} $cmd
