#!/bin/bash

set -euo pipefail

#####################################################
# This algorithm is implemented in the scikit-learn
# software package (http://scikit-learn.org/stable/).
#####################################################

trainingFilePath="$1"
testFilePath="$2"
classOptions="$3"
numCores="$4"
verbose="$5"

#export JOBLIB_START_METHOD="forkserver"

python3 AlgorithmScripts/Helper/sklearn_c_generic.py "$trainingFilePath" "$testFilePath" "$classOptions" "$numCores" "clf = ExtraTreesClassifier(n_estimators=50, criterion='entropy', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, max_leaf_nodes=None, bootstrap=False, oob_score=False, class_weight=None, n_jobs={n_jobs}, random_state=R_SEED, verbose=0, warm_start=False)"
#python3 AlgorithmScripts/Helper/sklearn_c_generic.py "$trainingFilePath" "$testFilePath" "$classOptions" "$numCores" "clf = ExtraTreesClassifier(n_estimators=50, criterion='entropy', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, max_leaf_nodes=None, bootstrap=False, oob_score=False, class_weight=None, n_jobs={n_jobs}, random_state=R_SEED, verbose=0, warm_start=False)" 2>&1 | python3 AlgorithmScripts/Helper/ReformatSklearnClassificationOutput.py "$classOptions" "$verbose"
