#!/bin/bash

set -euo pipefail

SL_DOCKER_IMAGE_NAME="$1"

echo Building Docker image $SL_DOCKER_IMAGE_NAME...

currentDir=$(pwd)
tmpDir=/tmp/build_local_docker
version=$(cat VERSION)

rm -rf $tmpDir
mkdir $tmpDir

cp -r AlgorithmScripts $tmpDir/
cp build.xml $tmpDir/
cp Dockerfile $tmpDir/
cp -r JavaCode $tmpDir/
cp LICENSE $tmpDir/
cp README.md $tmpDir/
cp -r scripts $tmpDir/
cp -r UserScripts $tmpDir/
cp VERSION $tmpDir/

cd $tmpDir

docker build -t srp33/${SL_DOCKER_IMAGE_NAME}:version${version} .
# | grep -v "tar: "

cd $currentDir
rm -rf $tmpDir
