#!/bin/bash

set -o errexit

#javaDir="/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Commands"
javaDir="/usr/bin"

currentDir=$(pwd)
buildDir=/tmp/shinylearner_build

rm -rfv $buildDir

mkdir -pv $buildDir/shinylearner/src/shinylearner
cp -rv java/src/shinylearner/* $buildDir/shinylearner/src/shinylearner
cp -v build.xml $buildDir/

cd $buildDir

find shinylearner -name *.java > sources_list.txt
$javaDir/javac @sources_list.txt
rm sources_list.txt

ant

mkdir -p $currentDir/release
rm -rf $currentDir/release/*

cp -v shinylearner.jar $currentDir/release/

cd $currentDir
rm -rf $buildDir
