#!/bin/bash

set -euo pipefail

callingDir=$(dirname $0)
callingFile=$(basename $0)
#helpFile=$callingDir/docs/$callingFile.md
#helpMessage="$(cat $helpFile)"
helpMessage="See https://github.com/srp33/ShinyLearner/blob/master/UserScripts/docs/${callingFile}.md for this command's documentation."

if [ $# -eq 0 ]; then
#    >&2 echo No arguments provided.
    >&2 echo
    >&2 echo "$helpMessage"
    >&2 echo
    exit 1
fi

quickExit=FALSE

for i in "$@"
do
  case $i in
    -h)
        echo
        echo "$helpMessage"
        echo
        quickExit=TRUE
    ;;
    -v)
        echo ShinyLearner version $(cat $(pwd)/VERSION).
        quickExit=TRUE
    ;;
  esac
done

if [[ "$quickExit" == "TRUE" ]]
then
  exit 0
fi
