#!/bin/bash

set -euo pipefail

callingDir=$(dirname $0)
callingFile=$(basename $0)
helpFile=$callingDir/docs/$callingFile
helpMessage="$(cat $helpFile)"

if [ $# -eq 0 ]; then
    echo No arguments provided.
    echo
	echo "$helpMessage"
    echo
    exit 1
fi

quickExit=FALSE

for i in "$@"
do
  case $i in
    -h)
        echo
        echo "$helpMessage"
        echo
        quickExit=TRUE
    ;;
    -v)
        echo ShinyLearner version $(cat $(pwd)/VERSION).
        quickExit=TRUE
    ;;
  esac
done

if [[ "$quickExit" == "TRUE" ]]
then
  exit 0
fi
