#!/bin/bash

command_exists () {
    type "$1" &> /dev/null ;
}

## Find out amount of memory available
function getMemAvailable {
  if command_exists free
  then
    mem=$(free -m | tail -n3 | awk '{print $2}' | head -n1)M # Gives total memory in MB (preferred over GB because it always rounds down)
  else
    mem=$(top -l 1 | awk '/PhysMem:/ {print $2}' | tr '[:upper:]' '[:lower:]')
  fi

  echo "$mem"
}

classPath=lib/paldb.jar

tmpDir=$(mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir')

function cleanup {
  rm -rf $tmpDir
}

cleanup
mkdir -p $tmpDir

trap cleanup INT TERM EXIT

errFile=/dev/null
if [[ "$debug" == "true" ]]
then
  errFile=$(mktemp $tmpDir/XXXXXXXXX)
fi

function printError {
  if [[ "$debug" == "true" ]]
  then
    cat $errFile
  fi
}

if [[ "$validationType" == "montecarlo" ]]
then
  iterationOutputHeader=Iteration
else
  iterationOutputHeader=Fold
fi
