#!/bin/bash

set -euo pipefail

source scripts/shared_functions

dataFiles="$1"
description="$2"
outerNumIterations="$3"
innerNumIterations="$4"
debug="$5"
classifAlgos="$6"
outPredictionsFile="$7"
outMetricsFile="$8"
outNestedPredictionsFile="${9}"
outNestedMetricsFile="${10}"
outNestedBenchmarkFile="${11}"
validationType="${12}"
randomSeed="${13}"

checkParam "$dataFiles" "data files"
checkParam "$description" "description"
checkParam "$outerNumIterations" "outer number of iterations"
checkParam "$innerNumIterations" "inner number of iterations"
checkParam "$debug" "debug"
checkParam "$classifAlgos" "classification algorithm(s)"
#checkParam "$outPredictionsFile" "output predictions file"
#checkParam "$outMetricsFile" "output metrics file"
#checkParam "$outNestedPredictionsFile" "output nested predictions file"
#checkParam "$outNestedMetricsFile" "output nested metrics file"
#checkParam "$outNestedBenchmarkFile" "output nested benchmark file"
checkParam "$validationType" "validation type"
checkValidationType "$validationType"

source scripts/setup

analysisDataFile=$tmpDir/data.gz

echo "Preparing for analysis..."
java -Xmx${mem} -jar shinylearner.jar RAW_DATA_FILES="$dataFiles" ANALYSIS_DATA_FILE="$analysisDataFile" DEBUG=$debug TEMP_DIR=$tmpDir 2> /dev/null

python scripts/ExtractSampleInfo.py "$analysisDataFile" "$description" $tmpDir/allid $tmpDir/classes

if [[ "$validationType" == "montecarlo" ]]
then
  python scripts/AssignTrainingTesting.py $tmpDir/allid $tmpDir/classes "$iterationOutputHeader" $tmpDir/ott $outerNumIterations $randomSeed
  python scripts/AssignTrainingTesting.py $tmpDir/ott $tmpDir/classes "Inner" $tmpDir/ie $innerNumIterations $randomSeed
else
  python scripts/AssignCrossValidation.py $tmpDir/allid $tmpDir/classes "$iterationOutputHeader" $tmpDir/ott $outerNumIterations $randomSeed
  python scripts/AssignCrossValidation.py $tmpDir/ott $tmpDir/classes "Inner" $tmpDir/ie $innerNumIterations $randomSeed
fi

## Prepare inner experiment files
python scripts/AddAlgorithmScripts.py $tmpDir/ie "$classifAlgos" $tmpDir/ie2


echo "Classifying for inner iterations..."
java -Xmx${mem} -jar shinylearner.jar ANALYSIS_DATA_FILE=$analysisDataFile EXPERIMENT_FILE=$tmpDir/ie2 DEBUG=$debug OUTPUT_BENCHMARK_FILE_PATH=$tmpDir/icb OUTPUT_PREDICTIONS_FILE_PATH=$tmpDir/ip TEMP_DIR=$tmpDir 2> /dev/null

echo "Calculating classification metrics for inner iterations..."
Rscript --vanilla scripts/CalculateClassificationMetrics.R "$tmpDir/ip" "$tmpDir/im"

echo "Parsing inner classification results..."
python scripts/ReformatInnerResults_Classification.py $tmpDir/im $tmpDir/ibrf

echo "Identifying best combination of algorithms..."
Rscript --vanilla scripts/SelectBestInnerResults_Classification.R $tmpDir/ibrf $tmpDir/ott $tmpDir/ocle 2> $errFile
printError $debug $errFile

echo "Classifying for outer iterations..."
java -Xmx${mem} -jar shinylearner.jar ANALYSIS_DATA_FILE=$analysisDataFile EXPERIMENT_FILE=$tmpDir/ocle DEBUG=$debug OUTPUT_PREDICTIONS_FILE_PATH=$tmpDir/op TEMP_DIR=$tmpDir 2> /dev/null

echo "Calculating classification metrics for outer iterations..."
Rscript --vanilla scripts/CalculateClassificationMetrics.R "$tmpDir/op" "$tmpDir/om"

echo "Preparing output files..."

if [[ "$outPredictionsFile" != "" ]]
then
  python scripts/ParseNestedResults.py $tmpDir/op $iterationOutputHeader $tmpDir/op.sorttemp
  sortFile $tmpDir/op.sorttemp "-k1,1 -k2,2n -k3" "$outPredictionsFile"
fi
if [[ "$outMetricsFile" != "" ]]
then
  python scripts/ParseNestedResults.py $tmpDir/om $iterationOutputHeader $tmpDir/om.sorttemp
  sortFile $tmpDir/om.sorttemp "-k1,1 -k2,2n -k3" "$outMetricsFile"
fi

if [[ "$outNestedPredictionsFile" != "" ]]
then
  python scripts/ParseNestedResults2.py $tmpDir/ip $iterationOutputHeader $tmpDir/ip.sorttemp
  sortFile $tmpDir/ip.sorttemp "-k1,1 -k2,2n -k3,3n -k4" "$outNestedPredictionsFile"
fi
if [[ "$outNestedMetricsFile" != "" ]]
then
  python scripts/ParseNestedResults2.py $tmpDir/im $iterationOutputHeader $tmpDir/im.sorttemp
  sortFile $tmpDir/im.sorttemp "-k1,1 -k2,2n -k3,3n -k4" "$outNestedMetricsFile"
fi
if [[ "$outNestedBenchmarkFile" != "" ]]
then
  python scripts/ParseNestedResults2.py $tmpDir/icb $iterationOutputHeader $tmpDir/icb.sorttemp
  sortFile $tmpDir/icb.sorttemp "-k1,1 -k2,2n -k3,3n -k4" "$outNestedBenchmarkFile"
fi

cleanup $tmpDir
