#!/bin/bash

echo "***********************************************************************" | tee -a $outLogFile
echo "Command that was executed for analysis on $(date):" | tee -a $outLogFile
echo | tee -a $outLogFile
echo "$0 $@" | tee -a $outLogFile
echo "***********************************************************************" | tee -a $outLogFile
echo
