#!/bin/bash

set -euo pipefail

errFile=/dev/null
if [[ "$verbose" == "true" ]]
then
  errFile=$(mktemp $tmpDir/XXXXXXXXX)
fi

if [[ "$validationType" == "montecarlo" ]]
then
  iterationOutputHeader=Iteration
else
  iterationOutputHeader=Fold
fi
