#!/bin/bash

body() {
  # See http://unix.stackexchange.com/questions/11856/sort-but-keep-header-line-at-the-top
  IFS= read -r header
  printf '%s\n' "$header"
  "$@"
}

function sortFile {
  inSortFile="$1"
  sortCriteria="$2"
  outSortFile="$3"

  if [[ "$inSortFile" == "" ]]
  then
    echo No input sort file specified.
    exit 1
  fi
  if [[ "$sortCriteria" == "" ]]
  then
    echo No sort criteria specified.
    exit 1
  fi
  if [[ "$outSortFile" == "" ]]
  then
    echo No output sort file specified.
    exit 1
  fi

  cat "$inSortFile" | body sort $sortCriteria > $outSortFile
}
