#!/bin/bash

mlflexDirPath="$1"
dataFilePath="$2"
callingScript="$3"

dirName=$(dirname $0)

algorithmAbbreviated=$(python $dirName/ParseAlgorithmName.py $callingScript)

Rscript --vanilla $dirName/mlr_fs_generic.R "$dataFilePath" "${algorithmAbbreviated}" 2>&1 | python $dirName/ReformatOutput.py
