#!/bin/bash

##########################################################
# This algorithm is implemented in the weka
# software package (http://www.cs.waikato.ac.nz/ml/weka/).
##########################################################

bash AlgorithmScripts/Helper/weka_ff_generic "$1" 'weka.attributeSelection.ReliefFAttributeEval -M -1 -D 1 -K 5 -W -s "weka.attributeSelection.Ranker -T -1.7976931348623157E308 -N -1"'
