#!/bin/bash

set -euo pipefail

#######################################################################################
# This algorithm is implemented in the mlr software package (http://mlr-org.github.io).
#######################################################################################

trainingFilePath="$1"
testFilePath="$2"
classOptions="$3"

Rscript --no-save --no-restore --no-site-file --no-init-file --no-environ --max-ppsize=500000 AlgorithmScripts/Helper/mlr_c_generic.R "$trainingFilePath" "$testFilePath" "$classOptions" "'classif.boosting', boos=FALSE, mfinal=100, coeflearn='Freund'" 2>&1 | python AlgorithmScripts/Helper/ReformatMlrClassificationOutput.py "$classOptions"
