#!/bin/bash

set -euo pipefail

#####################################################
# This algorithm is implemented in the scikit-learn
# software package (http://scikit-learn.org/stable/).
#####################################################

dataFilePath="$1"

python AlgorithmScripts/Helper/sklearn_f_generic.py "$dataFilePath" "score" "F, score = f_classif(train_X, train_y)" 2>&1 | python AlgorithmScripts/Helper/ReformatSklearnOutput.py
