#!/bin/bash

#####################################################
# This algorithm is implemented in the scikit-learn
# software package (http://scikit-learn.org/stable/).
#####################################################

bash "$(dirname $0)"/../../../../Helper/sklearn_fs_generic "$1" "$0"
