#!/bin/bash

set -euo pipefail

#####################################################
# This algorithm is implemented in the scikit-learn
# software package (http://scikit-learn.org/stable/).
#####################################################

dataFilePath="$1"
numCores="$2"

python AlgorithmScripts/Helper/sklearn_f_generic.py "$dataFilePath" "$numCores" "rfe" "selector = RFE(RandomForestClassifier(n_estimators=50, random_state=R_SEED), n_features_to_select=1, step=0.1)" 2>&1 | python AlgorithmScripts/Helper/ReformatSklearnOutput.py
